version: '3'
services:
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: Postgres
      PGDATA: certification10pgdata
    ports:
      - '5432:5432'

volumes:
  certification10pgdata:
